last step checks for unused variable

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,7 +67,8 @@ jobs:
 
       - name: Check vulture output
         run: |
-          if [ -n "$(vulture h_transport_materials/property_database )" ]; then
-            echo "unused variable"
+          vulture_output=$(vulture h_transport_materials/property_database) || true
+          if [[ $vulture_output == *"unused variable"* ]]; then
+            echo "Error: Unused variables found."
             exit 1
           fi
